This is red and small.
This is red and a sphere.
The sphere is red and small.
The sphere is red and in the pantry.
This is red and in the pantry.
This is small, green, and in the pantry.
This is a sphere and red.
This is in the pantry and red.
The sphere is green and the orange triangle is blue.
The sphere is green and this is blue.
Pick up the sphere and store the sphere in the pantry.
Pick up the sphere and store it in the pantry.
Stack the red triangle and the green sphere.
Stack the red triangle, the medium block and the large block.
