The name of the game is frogs-and-toads-puzzle.
The goal is that all the red blocks are on the red locations and the all blue blocks are on the blue locations.
You can move a red block from a location onto a clear location that is to the left of the original location.
You can move a red block onto a clear location to the left of the block.
You can move a blue block onto a clear location that is to the right of the block.
If a clear location is to the left of a location below a blue block and the location is to the left of the latter location below a red block then you can move the red block to the clear location.
If a location below a red block is to the right of a location below a blue block and the second location is to the right of a clear location then you can move the red block to the clear location.
