The current state is the initial state.
The current state is the final state.
Attend to the red object.
Ignore the relation that is named below.
Ignore the relation named below.
Attend to the relation that is named below.
Attend to the relation named below.
You can move a free red block onto a clear location.
If all the green blocks are on their locations then you can move a red block onto a clear location.
Ignore below.
The game is called tictactoe.
The puzzle is called tower-of-hanoi.
The game is tic-tac-toe.
The goal is three-in-a-row.
