Green the store block.
Yes.
No.
Finished.
Purple is a color.
The sphere is green.
The red triangle is on the big green block.
The red triangle.
The red triangle on the large green block.
The red one.
The game is tictactoe.
The task is done.
This is red.
This is a big red triangle.
What is inside the pantry?
What is this?
What size is the green sphere?
What is on the red triangle?
Where is the red triangle?
Clean the kitchen.
Discard the large green block.
Store the large green block on the red triangle.
Put the green sphere in the pantry.
Turn the stove on.
Put down the green sphere in the pantry.
move the orange triangle on the red triangle to the stove.
Is the green sphere on the table?
Is the red arch to the right of the blue l-block?
Is this green?
Is the green block a sphere?
Right is a relation.
grab the sphere.
store the sphere.
store the medium red sphere.
