Stop.
Go.
Forward.
Go forward.
Drive forward.
Go down the hall.
Orient north.
Orient s.
Face east.
Face west.
Turn around.
Turn right.
Turn left.
Follow the left wall.
Follow the right wall.
Go to the waypoint.
Go to the kitchen.
Drive to the kitchen.
Go to the starting location.
Go to your starting location.
Go to the waypoint.
Pick up the box.
Put down the box.
You are in the kitchen.
The soda is in the kitchen.
Go forward until you see an intersection.
Explore until you see a soda.
Drive until you sense a wall.
Go until there is a doorway.
Drive down the hall until you reach the end.
Follow the right wall until there is a doorway.
Follow the right wall until you see two doors.
Follow the right wall until you reach the end.
Drive forward one meter.
Drive slowly to the kitchen.
Deliver the box to the kitchen.
Take the box to the kitchen.
Take the box to the kitchen.
The goal is that the box is in the kitchen.
The goal is that you are not holding the box.
The goal is that the box is in the kitchen and the sphere is purple.
The sphere is red.
The goal is that the box is in the kitchen andx you are not holding the box.
