The name of the game is Othello.
The name of an action is capture.
If a piece is white then it is an enemy piece.
A white piece is an enemy piece.
An enemy piece is white.
If a location is below an enemy piece then the location is occupied.
If the locations between a clear location and a captured location are occupied then you can place a piece on the clear location.
If the locations between a clear location and a captured location are below enemy pieces then you can place a piece on the clear location.
The goal is that all locations are covered and the number of captured locations is more than the number of occupied locations.
