Done.
The task is finished.
The task is done.
Finished.
You are done.
No.
Yes.
Octagon is a shape.
Study is a location.
Green is a color.
Mauve is color.
Taupe is a color.
Taupe is a color.
What is inside the pantry?
What is this?
What is inside the pantry
What is on the red triangle?
Where is the red triangle?
The name of the action is place-block.
The name of the game is tic-tac-toe.
The game is tictactoe.
The large one is red.
This is orange.
This one is orange.
This is a big triangle.
The sphere is green.
The medium block is green.
The big triangle is red.
The red triangle is clear.
The sphere is cooked.
The red triangles are on the pantry.
The stove is off.
The red triangle is on the stove.
The red triangle is on the big green block.
A location is not below a red block.
An orange block is on a small location.
The purple block is not on a red location.
The red triangle is behind the stove.
The red triangle is to the left of the stove.
All of the red triangles are in the pantry.
All the red triangles are in the pantry.
All red triangles are in the pantry.
The medium block is smaller than the large block.
Turn on the stove.
Open the pantry.
Close the pantry.
Discard the large green block.
Cook the red triangle.
Serve the red triangle.
Organize the pantry.
Set the table.
Store the sphere.
Store the green block.
Clean the pantry.
Clean pantry.
Clean small red triangle.
Rosie clean the pantry.
Rosie, clean the pantry.
Put the green sphere in the pantry.
Put the green one in the pantry.
Put that in the pantry.
Put this in the pantry.
Put it on this.
Put down the green sphere in the pantry.
Pick up the green sphere.
Pick up the green block on the stove.
Store the large green sphere on the red triangle.
Move the orange triangle on the red triangle to the stove.
Put the green sphere in front of the pantry.
Put the green sphere next to the pantry.
Move the green sphere to the right of the garbage.
Move the green sphere to the left of the garbage.
Move the green rectangle to the left of the large green rectangle to the pantry.
Move the green rectangle that is to the left of the large green rectangle to the pantry.
Wait for one minute.
Wait for two minutes.
Wait until the sphere is cooked.
This is larger than the green sphere.
Pick up this.
Pick this up.
Put this on the stove.
Pick up that.
Pick up the purple object.
Put it on the stove.
Pick it up.
Pick the unknown.
Newverb the sphere.
Newverb the sphere.
Newverb2 the sphere in the pantry.
Newverb2 the sphere in the pantry.
Newverb3 in the pantry.
Newverb3 in the pantry.
Store the pantry.
Put the sphere in the red triangle.
Transport is an action.
In-a-row is a relation.
What color is the large sphere?
What shape is this?
What size is the red triangle?
Is the large orange block a sphere?
Is this a sphere?
Is the large sphere green?
Is this red?
Is the small orange triangle behind the green sphere?
Is the green sphere on the table?
Is the large triangle to the right of the green sphere?
Drive to the wall.
Go until there is a doorway.
Drive until you sense a wall.
Go forward until you see the intersection.
Go to waypoint.
Go to the waypoint.
Orient s.
Orient north.
Stop.
Follow the right wall.
Follow the left wall.
Forward.
Go.
Drive forward.
Go forward.
Turn around.
Turn right.
Turn left.
Pick the red box.
Pick the green block that is small.
Pick a green block that is small.
Pick the green block that is on the stove.
Pick a green block that is on the stove.
Pick a green block that is on a stove.
Pick a green block that is larger than the green box.
If the green box is large then go forward.
If you see the soda then pick it up.
If you see the soda then pick it up.
The green large sphere is between a clear location and a captured location.
The green large sphere is between the purple triangle and the orange triangle.
The enemy locations are between a clear square and a captured square.
The captured blocks are on clear locations.
The blocks are on locations.
Carefully pick up the small green block.
String Test: string test.
Say string test.
