Turn on the stove.
Turn off the stove.
Turn around.
Turn right.
Turn left.
Follow the left wall.
Follow the right wall.
Move the green sphere to the right of the garbage.
Is the large triangle to the right of the green sphere?
The goal is that all the missionaries are on the right side of the river and all the cannibals are on the right side of the river.
Attend to the red object.
The medium block is smaller than the large block.
