The name of the game is tic-tac-toe.
The name of an action is place-block.
Move a free red block onto a clear location.
If a location is clear then you can move a free red block onto the location.
If a location is below a red block then it is captured.
The goal is that three captured locations are linear.
The goal is that three captured locations are in a line.
The goal is that three red blocks are ontop their locations and those locations are linear.
The goal is that three red blocks are ontop their locations and those locations are in a row.
