The name of the puzzle is peg-solitaire.
if a location is not below an object then it is clear.
if a location is below an object then it is covered.
the goal is that the number of covered locations is one.
if the location below a block is between a clear location and a covered location then you can move the block onto the garbage and a block on the covered location onto the clear location.
if the location below a block is between a clear location and a covered location then you can move the block onto the garbage plus you can move a block on the covered location onto the clear location.
